### PR TITLE
Change build system to Dune

### LINKED ISSUE #59: not compiling on ubuntu and osx
- [x] on Ubuntu because of `ld` for some reason that I don't understand
- [ ] on OSX because of the use of a GNU option of `ar`

### PR DESCRIPTION
**Pull request by Niols**
This PR removes the dependency in OCamlBuild and uses Dune as the new build system. The sides effects of this are:

- The compilation is a bit faster: 18s before, 13s now on my machine. Dune usually provides a much larger speedup because of it's cleverer parallelisation. Not in our case, because most of the time is spent by one OCaml process on CST.ml.

- We need to **drop support for OCaml < 4.04**. Prior to this version, PPXes that we use weren't compatible with Dune.

- The fact that Dune compiles by default with all warnings made me clean some code (see 6df6186).

- Dune does most of the work for the C compilation. The only remaining thing (and I'm working on making that cleaner) is to merge Morbig's `.o` file containing everything in Morbig and its dependencies with the `.o` file from the stubs. This last part can be done using POSIX options for `ar`, meaning that we get **the support for OSX**.

- Also, since we got rid of the use of a Makefile in the OPAM package, we can almost get the support for Windows. All it takes is to remove the use of `ar` (which should happen).

@yurug I have changed a lot of things. In particular, the cleanup commits may clash with other PRs of yours…

@treinen This means that the Debian package will have to follow the change too.

fix #59

### CODE REVIEW

**Comment by treinen** [comment]
looks OK to me

**Comment by Niols** [comment]
But… there is a .opam at the root of the project, isn't there?

**Comment by treinen** [comment]
No, there is no .opam file. -Ralf.

On Thu, Feb 14, 2019 at 04:11:38AM -0800, Nicolas Jeannerod wrote:
> But… there is a .opam at the root of the project, isn't there?
> 
> Le 14 février 2019 11:38:43 GMT+01:00, Ralf Treinen <notifications@github.com> a écrit :
> >treinen requested changes on this pull request.
> >
> >I get (with dune 1.6.2):
> >
> >````
> >% make
> >dune build @install
> >File "src/dune", line 3, characters 1-21:
> >3 |  (public_name morbig)
> >     ^^^^^^^^^^^^^^^^^^^^
> >Error: You cannot declare items to be installed without adding a
> ><package>.opam file at the root of your project.
> >To declare elements to be installed as part of package "morbig", add a
> >"morbig.opam" file at the root of your project.
> >make: *** [Makefile:4: build] Error 
> >''''
> >
> >
> >
> >-- 
> >You are receiving this because you authored the thread.
> >Reply to this email directly or view it on GitHub:
> >https://github.com/colis-anr/morbig/pull/62#pullrequestreview-203672937
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/colis-anr/morbig/pull/62#issuecomment-463604856

-- 
Ralf Treinen
Institut de Recherche en Informatique Fondamentale
Équipe Preuves, Programmes et Systèmes
Université Paris Diderot, Paris, France.
http://www.irif.fr/~treinen/

**Comment by Niols** [comment]
Well, looking at the `dune` branch, I can see a `morbig.opam` file: https://github.com/colis-anr/morbig/tree/dune

**Comment by Niols** [comment]
Yes, not a `.opam` but a `morbig.opam`, sorry.

**Comment by treinen** [comment]
in fact my git repo was in a inconsitent state (unmerged changes). Sorry

Now I get

````
% make
dune build @install
         ppx src/CST.pp.ml (exit 1)
(cd _build/default && .ppx/ecc96117b0cf6b8e6682a5d348b0a70e/ppx.exe --cookie 'library-name="morbig"' -o src/CST.pp.ml --impl src/CST.ml --dump-ast)
File "src/CST.ml", line 61, characters 3-11:
Error: Cannot locate deriver visitors
''''

**Comment by treinen** [comment]
@Niols: what version of visitors are you using? The visitors commit log indicates some recent changes to make visitors work in conjunction with dune, but this is not yet a released version of visitors, and I do not want to tweek libraries in debian since we are already in the middle of freeze for buster.

**Comment by Niols** [comment]
So, like we said, visitors was fixed to work with Dune in may 2018. There is an OPAM release:

https://github.com/ocaml/opam-repository/blob/master/packages/visitors/visitors.20180513/opam

using an archive on François's website, but no git tag:

https://gitlab.inria.fr/fpottier/visitors/tags

It is probably a bit late for Debian Buster, but this PR is not that important to Debian. Could we still ask François to tag this version?

**Comment by treinen** [comment]
I just sent a mail to Francois. Anyway, since there are no dependencies in the debian archive on a particular version of ocaml-visitors but just a build-dependency of morbig, and since morbig 
compiles fine with the new version of visitors I can upload ocaml-visitors 20180513 without 
problems.

-Ralf.

**Comment by Niols** [comment]
Does that mean we should merge this?

**Comment by treinen** [comment]
OK for the merge from my side.

**Comment by Niols** [comment]
Waiting for @yurug's green light then.

**Pull request merged**
