### PR TITLE
Cleanup Dune compilation

### LINKED ISSUE #64: Rename `Morbig.API` → `Morbig`?
Now that we compile with Dune, it's super easy to make all the functions of API directly accessible from the `Morbig` module. `Morbig.API.parse_file` would simply be `Morbig.parse_file`. The other modules would still be accessible naturally (`Morbig.CST.program`, for instance).

This can be a breaking change. Actually, this can also be done in a retro-compatible way (by providing access to this functions both directly in the `Morbig` module and in the `Morbig.API` module) but I'd rather take advantage of the fact that we are preparing breaking changes anyway to do this one.

I would personally vote for that and it's a matter of minutes (if not seconds) for me to do this change. What do you think, @treinen, @yurug?

### PR DESCRIPTION
**Pull request by Niols**
This PR:
- removes the workaround with `ar`.
- renames the entry point of Morbig from `Morbig.API` to `Morbig`.
- renames `MorbigOptions` into `Options` now that we have Dune to take care of overlapping names.
- allows for customization of what is exported in the Morbig library (see `morbig.ml`)

fix #64

### CODE REVIEW

**Comment by Niols** [comment]
By the way, looking at all the module names in `morbig.ml`, I think that lots of them could be hidden. One just has to remove the corresponding like from that file. I'm not sure which ones should be deleted, but that could be nice. Don't hesitate to push to the `dune-2` branch in that case.

**Comment by Niols** [comment]
Also, we have a lot of modules. Maybe we could/should reorganize them in subdirectories? (Or even in sub-libraries?)

**Comment by yurug** [comment]
A potential reorganization should be done in a distinct PR, IMHO.

**Comment by Niols** [comment]
Indeed, and maybe only after your bug merge. Actually, I should maybe postpone this PR and wait for yours?

**Pull request merged**
